### ISSUE TITLE
데브이벤트 저장소로 넛지 관련!

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Chrome-Extention#1]
@kimud6003  님~ 열심히 작업중이시군요 👍 👍 

다름이 아니라 데이터 출처 및 원 저장소로 넛지 관련하여 제안드립니다.

> Github Dev Event에서 제공하는 정보입니다.

위의 문구가 하단 이미지의 파란색 박스에 들어가면 어떨까 제안드립니다^^ (문구를 클릭하면 https://github.com/brave-people/Dev-Event 로 이동하고요!)

![image](https://user-images.githubusercontent.com/28642484/143596878-9dffa931-d5b4-41f5-8eba-a6c6293d97b2.png)

크롬 확장앱을 사용하시는 분들이 데브 이벤트 깃헙 저장소 뿐만 아니라 다른 분들이 운영하시는 이메일, 안드로이앱 그리고 앞으로 나올 웹까지 넛지가 되었으면 해서요! (역시 웹이 나온다면 배너하 데브 이벤트 패밀리 프로젝트를 소개하고요~)

서버 개발자인 저보다 디자인에 조예가(?) 깊으시기에 넣는 위치에 대해서 어떻게 생각하시는지 의견 부탁드립니다!

감사합니다^^

**Comment by kimud6003** [comment]
@KoEonYack 앗! 면접 준비 때문에 늦게 봤습니다!
좋은 아이디어 말씀해주셔서 감사합니다. 
저도 만들면서 해당 링크를 달아주면 좋을거 같았는데 위치를 말씀해 주셔서 감사합니다.  
해당 아이디어를 반영해서 12월 4일 중으로  완성해보겠습니다!

**Comment by KoEonYack** [comment]
@kimud6003 
면접 준비와 플젝도 하시는 것이군요~!
즐거운 개발되세요~! 👍
